### ISSUE TITLE
don't want to distribute none-public map

### ISSUE THREAD

**Issue by wafter9** [sc2-arcade-watcher/server#6]
The map was locked and none-public upload
But it is public!

**Comment by Talv** [comment]
Any map is distributed the moment it is being published on Battle.net - please read the custom games policy: https://www.blizzard.com/en-us/legal/2749df07-2b53-4990-b75e-a7cb3610318b/custom-game-acceptable-use-policy

sc2arcade.com is not distributing maps, Blizzard is. I'm not in power of that. The only difference is that website makes it easier to browse the maps, and also find maps which are normally unlisted in the game - aka `private`.

Furthermore the website doesn't process published archive file (`.s2ma`) - if the file was published as locked, then it'll stay as that. Available download links point to Blizzard servers. The game client uses the same links to download map related files to local cache - the moment the map is viewed. Then tools such as [s2mdec](https://github.com/sc2-arcade-watcher/s2mdec) can be used to obtain archive file - regardless of map's visibility settings (public/private).

However, any map author has ability to disable these links, if their presence on sc2arcade.com is still perceived as an issue.

In order to do so, one needs to authorize on the website using Battle.net account.
![image](https://user-images.githubusercontent.com/6976458/104436425-deb3b100-558d-11eb-96aa-5ac0fe2cdd89.png)

Then proceed to settings, and untick all options that mention "download".
![image](https://user-images.githubusercontent.com/6976458/104436443-e6735580-558d-11eb-9757-6fbdbc43c5a6.png)

I hope that clears things up. If not, please reopen ticket, and elaborate further about your problem.
